language: erlang
otp_release:
  - 17.1
  - 17.0
before_install:
  - wget http://s3.hex.pm/builds/elixir/v1.0.0.zip
  - unzip -d elixir v1.0.0.zip
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - export MIX_ENV=test
  - mix local.hex --force
  - mix deps.get
  - mix deps.compile
script: mix test
